version: "3.8"

services:
  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    env_file:
      - ./auth-service/.env
    command: node src/index.js
    ports:
      - "3001:3000"

  course-service:
    build:
      context: ./course-service
    container_name: course-service
    env_file:
      - ./course-service/.env
    command: node src/index.js
    ports:
      - "3002:3001"

  enrollment-service:
    build:
      context: ./enrollment-service
    container_name: enrollment-service
    env_file:
      - ./enrollment-service/.env
    command: node src/index.js
    ports:
      - "3003:3002"

  notification-service:
    build:
      context: ./notification-service
    container_name: notification-service
    env_file:
      - ./notification-service/.env
    command: node src/index.js
    ports:
      - "3004:3006"

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    env_file:
      - ./api-gateway/.env
    depends_on:
      auth-service:
        condition: service_started
      course-service:
        condition: service_started
      enrollment-service:
        condition: service_started
      notification-service:
        condition: service_started
    command: node src/index.js
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    env_file:
      - ./frontend/.env
    depends_on:
      api-gateway:
        condition: service_started
    command: npm run dev -- --host 0.0.0.0 --port 5173
    ports:
      - "5173:5173"